apiVersion: v1
kind: Service
metadata:
  name: myservice
  labels:
    app: myapp
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 31088
  selector:
    app: myapp
