# name: Trigger Workflow in Another Repository

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
# on:
#   workflow_dispatch:
#     inputs:
#       repository:
#         description: 'Kundankkrishna/MyApplication'
#         required: true
#       workflow:
#         description: 'Build and Deploy the application'
#         required: true

# jobs:
#   trigger_workflow:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Trigger Workflow
#         run: |
#           curl -X POST \
#             -H "Authorization: Bearer ${{ secrets.PAT }}" \
#             -H "Accept: application/vnd.github.v3+json" \
#             https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.inputs.repository }}/actions/workflows/${{ github.event.inputs.workflow }}/dispatches \
#             -d '{"ref":"main"}'
